USE [master]
GO

/****** Object:  Database [CData]    Script Date: 11.11.2018 12:00:08 ******/
CREATE DATABASE [CData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CData] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CData] SET ARITHABORT OFF 
GO

ALTER DATABASE [CData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CData] SET  MULTI_USER 
GO

ALTER DATABASE [CData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CData] SET  READ_WRITE 
GO

