//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mission()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int CounterpartyID { get; set; }
        public int EmployeeID { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool Completed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Counterparty Counterparty { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
