//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public int CounterpartyID { get; set; }
        public int EmployeeID { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool Completed { get; set; }
    
        public virtual Counterparties Counterparties { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
